import type { NormalizedDeal } from "@/lib/types/deals"

const now = Date.now()
const day = 24 * 60 * 60 * 1000

export const SAMPLE_DEALS: NormalizedDeal[] = [
  {
    id: "sample-1",
    origin: "AMS",
    destination: "Barcelona",
    destinationCity: "Barcelona",
    country: "Spanje",
    currentPrice: 189,
    originalPrice: 289,
    discountPercentage: 35,
    airline: "KLM",
    departureDate: new Date(now + 7 * day).toISOString(),
    returnDate: new Date(now + 12 * day).toISOString(),
    dealExpiration: new Date(now + 36 * 60 * 60 * 1000).toISOString(),
    seatsAvailable: 5,
    affiliateUrl: "#",
    bookingUrl: "https://www.booking.com", // placeholder
    imageUrl: "/barcelona-sagrada-familia-park-guell.png",
    airlineLogoUrl: "/klm-logo.png",
    rating: 4.8,
    reviewCount: 182,
    bookingsToday: 26,
    category: "Citytrip",
    partner: "booking",
    isFeatured: true,
    isDealOfDay: true,
    isActive: true,
    isSample: true,
  },
  {
    id: "sample-2",
    origin: "AMS",
    destination: "Istanbul",
    destinationCity: "Istanbul",
    country: "Turkije",
    currentPrice: 139,
    originalPrice: 219,
    discountPercentage: 37,
    airline: "Turkish Airlines",
    departureDate: new Date(now + 10 * day).toISOString(),
    returnDate: new Date(now + 16 * day).toISOString(),
    dealExpiration: new Date(now + 72 * 60 * 60 * 1000).toISOString(),
    seatsAvailable: 8,
    affiliateUrl: "#",
    bookingUrl: "https://www.turkishairlines.com",
    imageUrl: "/istanbul-hagia-sophia-bosphorus.png",
    airlineLogoUrl: "/turkish-airlines-logo.png",
    rating: 4.7,
    reviewCount: 143,
    bookingsToday: 32,
    category: "Citytrip",
    partner: "booking",
    isFeatured: true,
    isActive: true,
    isSample: true,
  },
  {
    id: "sample-3",
    origin: "AMS",
    destination: "Rome",
    destinationCity: "Rome",
    country: "Italië",
    currentPrice: 169,
    originalPrice: 259,
    discountPercentage: 35,
    airline: "ITA Airways",
    departureDate: new Date(now + 14 * day).toISOString(),
    returnDate: new Date(now + 20 * day).toISOString(),
    dealExpiration: new Date(now + 60 * 60 * 60 * 1000).toISOString(),
    seatsAvailable: 4,
    affiliateUrl: "#",
    bookingUrl: "https://www.ita-airways.com",
    imageUrl: "/rome-colosseum-vatican.png",
    airlineLogoUrl: "/ita-airways-logo.png",
    rating: 4.6,
    reviewCount: 201,
    bookingsToday: 18,
    category: "Cultuur",
    partner: "booking",
    isFeatured: false,
    isActive: true,
    isSample: true,
  },
  {
    id: "sample-4",
    origin: "AMS",
    destination: "New York",
    destinationCity: "New York",
    country: "Verenigde Staten",
    currentPrice: 429,
    originalPrice: 599,
    discountPercentage: 28,
    airline: "Delta Airlines",
    departureDate: new Date(now + 21 * day).toISOString(),
    returnDate: new Date(now + 28 * day).toISOString(),
    dealExpiration: new Date(now + 96 * 60 * 60 * 1000).toISOString(),
    seatsAvailable: 6,
    affiliateUrl: "#",
    bookingUrl: "https://www.delta.com",
    imageUrl: "/new-york-city-skyline.png",
    airlineLogoUrl: "/delta-airlines-logo.png",
    rating: 4.9,
    reviewCount: 312,
    bookingsToday: 41,
    category: "Verre reis",
    partner: "booking",
    isFeatured: false,
    isActive: true,
    isSample: true,
  },
]

export function getSampleDeals(): NormalizedDeal[] {
  return SAMPLE_DEALS.map((deal, index) => ({ ...deal, id: `${deal.id}-${index}` }))
}
